package com.example.motsi.core.wizard.impl.presentation.consts

const val WIZARD_ICON_KEY = "ICON_KEY"
const val WIZARD_TITLE_KEY = "TITLE_KEY"
const val WIZARD_SUBTITLE_KEY = "SUBTITLE_KEY"
const val WIZARD_HINT_KEY = "HINT_KEY"
const val WIZARD_SEARCH_QUERY_KEY = "SEARCH_QUERY_KEY"
const val WIZARD_DIVIDER_FLAG_KEY = "DIVIDER_FLAG_KEY"
const val WIZARD_FIELD_ACTION_KEY = "ON_FIELD_CLICK_ACTION_KEY"
const val WIZARD_NAVIGATION_ACTION_KEY = "NAVIGATION_ACTION_KEY"